"""Añadir campo detalles a la tabla cotizaciones

Revision ID: 93e28bf0629d
Revises: 
Create Date: 2025-11-19 22:20:43.898513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e28bf0629d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detalles', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizaciones', schema=None) as batch_op:
        batch_op.drop_column('detalles')

    # ### end Alembic commands ###
